"""
CIA-SIE Core Enumerations
=========================

Defines all enumeration types used throughout the system.
These enums are immutable and represent the constitutional vocabulary of the platform.

GOVERNED BY: Section 0B (Analysis Definition)
"""

from enum import Enum


class SignalType(str, Enum):
    """
    Classification of signal origin.

    Per Gold Standard Specification Section 5.3:
    - HEARTBEAT: Periodic signal at configured interval
    - STATE_CHANGE: Signal triggered by condition change
    - BAR_CLOSE: Signal sent at bar close (freshness update)
    - MANUAL: User-triggered on-demand signal
    """

    HEARTBEAT = "HEARTBEAT"
    STATE_CHANGE = "STATE_CHANGE"
    BAR_CLOSE = "BAR_CLOSE"
    MANUAL = "MANUAL"


class Direction(str, Enum):
    """
    Signal directional bias.

    Per Gold Standard Specification Section 5.3:
    - BULLISH: Positive/upward bias indicated by chart
    - BEARISH: Negative/downward bias indicated by chart
    - NEUTRAL: No directional bias indicated

    NOTE: The system does NOT resolve conflicts between directions.
    Contradictions are EXPOSED, not RESOLVED (Section 0B.5).
    """

    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


class FreshnessStatus(str, Enum):
    """
    Data freshness classification.

    Per Gold Standard Specification Section 5.3 and SDD v4.0:
    - CURRENT: Data from current/most recent bar
    - RECENT: Data within expected update frequency
    - STALE: Data older than expected update frequency
    - UNAVAILABLE: Data could not be retrieved

    NOTE: Freshness is purely DESCRIPTIVE - it does NOT invalidate
    or suppress data. All data is displayed regardless of freshness.
    (Section 0C - Automation Boundaries)
    """

    CURRENT = "CURRENT"
    RECENT = "RECENT"
    STALE = "STALE"
    UNAVAILABLE = "UNAVAILABLE"


class BasketType(str, Enum):
    """
    Analytical basket classification.

    Per Gold Standard Specification Section 5.3:
    - LOGICAL: Charts grouped by analytical function
    - HIERARCHICAL: Charts grouped by importance/sequence (user-defined)
    - CONTEXTUAL: Charts grouped by situational relevance
    - CUSTOM: User-defined grouping

    CRITICAL: Baskets exist ONLY in the UI layer.
    They do NOT affect processing (ADR-002).
    """

    LOGICAL = "LOGICAL"
    HIERARCHICAL = "HIERARCHICAL"
    CONTEXTUAL = "CONTEXTUAL"
    CUSTOM = "CUSTOM"


class NarrativeSectionType(str, Enum):
    """
    Types of narrative sections generated by the AI.

    Per Gold Standard Specification Section 14.2:
    - SIGNAL_SUMMARY: Description of what a chart's signal means
    - CONTRADICTION: Plain-English explanation of conflict
    - CONFIRMATION: Description of aligned signals
    - FRESHNESS: Data age explanation

    NOTE: All narrative types are DESCRIPTIVE, never PRESCRIPTIVE.
    """

    SIGNAL_SUMMARY = "SIGNAL_SUMMARY"
    CONTRADICTION = "CONTRADICTION"
    CONFIRMATION = "CONFIRMATION"
    FRESHNESS = "FRESHNESS"


class ValidationStatus(str, Enum):
    """
    Status of AI response validation.

    Per Gold Standard Specification Section 14.4:
    All AI responses must be validated for constitutional compliance.

    - VALID: Response passed all validation checks
    - INVALID: Response contains prohibited content
    - REMEDIATED: Response was modified to achieve compliance
    """

    VALID = "VALID"
    INVALID = "INVALID"
    REMEDIATED = "REMEDIATED"


class AIModelTier(str, Enum):
    """
    Claude model tiers for dynamic selection.

    - HAIKU: Fast and cheap, for simple queries
    - SONNET: Balanced, for standard analysis
    - OPUS: Most capable, for complex analysis
    """

    HAIKU = "HAIKU"
    SONNET = "SONNET"
    OPUS = "OPUS"


class UsagePeriod(str, Enum):
    """
    Time periods for AI usage tracking.
    """

    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class MessageRole(str, Enum):
    """
    Roles in a conversation.
    """

    USER = "user"
    ASSISTANT = "assistant"
