/**
 * CIA-SIE Frontend Enum Definitions
 * 
 * These enums match the backend Python enums exactly.
 * GOVERNED BY: Section 0B (Analysis Definition) - ADAPTER_FINANCIAL_SERVICES.md
 */

/**
 * Signal directional bias.
 * 
 * NOTE: The system does NOT resolve conflicts between directions.
 * Contradictions are EXPOSED, not RESOLVED (Constitutional Rule CR-002).
 */
export enum Direction {
  BULLISH = 'BULLISH',
  BEARISH = 'BEARISH',
  NEUTRAL = 'NEUTRAL',
}

/**
 * Data freshness classification.
 * 
 * NOTE: Freshness is purely DESCRIPTIVE - it does NOT invalidate data.
 * All data is displayed regardless of freshness (Constitutional Rule CR-003).
 */
export enum FreshnessStatus {
  CURRENT = 'CURRENT',
  RECENT = 'RECENT',
  STALE = 'STALE',
  UNAVAILABLE = 'UNAVAILABLE',
}

/**
 * Classification of signal origin.
 */
export enum SignalType {
  HEARTBEAT = 'HEARTBEAT',
  STATE_CHANGE = 'STATE_CHANGE',
  BAR_CLOSE = 'BAR_CLOSE',
  MANUAL = 'MANUAL',
}

/**
 * Analytical basket classification.
 * 
 * CRITICAL: Baskets exist ONLY in the UI layer.
 * They do NOT affect processing (ADR-002).
 */
export enum BasketType {
  LOGICAL = 'LOGICAL',
  HIERARCHICAL = 'HIERARCHICAL',
  CONTEXTUAL = 'CONTEXTUAL',
  CUSTOM = 'CUSTOM',
}

/**
 * Types of narrative sections generated by AI.
 * 
 * NOTE: All narrative types are DESCRIPTIVE, never PRESCRIPTIVE.
 */
export enum NarrativeSectionType {
  SIGNAL_SUMMARY = 'SIGNAL_SUMMARY',
  CONTRADICTION = 'CONTRADICTION',
  CONFIRMATION = 'CONFIRMATION',
  FRESHNESS = 'FRESHNESS',
}

/**
 * Status of AI response validation.
 */
export enum ValidationStatus {
  VALID = 'VALID',
  INVALID = 'INVALID',
  REMEDIATED = 'REMEDIATED',
}

/**
 * Claude model tiers for dynamic selection.
 */
export enum AIModelTier {
  HAIKU = 'HAIKU',
  SONNET = 'SONNET',
  OPUS = 'OPUS',
}

/**
 * Time periods for AI usage tracking.
 */
export enum UsagePeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}

/**
 * Message roles in conversation.
 */
export enum MessageRole {
  USER = 'user',
  ASSISTANT = 'assistant',
}

