// ============================================================================
// ENUMERATIONS
// Matches backend enums exactly: src/cia_sie/core/enums.py
// ============================================================================

/**
 * Signal directional bias
 * @see src/cia_sie/core/enums.py - Direction
 */
export type Direction = 'BULLISH' | 'BEARISH' | 'NEUTRAL'

/**
 * Classification of signal origin
 * @see src/cia_sie/core/enums.py - SignalType
 */
export type SignalType = 'HEARTBEAT' | 'STATE_CHANGE' | 'BAR_CLOSE' | 'MANUAL'

/**
 * Data freshness classification
 * @see src/cia_sie/core/enums.py - FreshnessStatus
 */
export type FreshnessStatus = 'CURRENT' | 'RECENT' | 'STALE' | 'UNAVAILABLE'

/**
 * Analytical basket classification
 * CRITICAL: Baskets exist ONLY in the UI layer. They do NOT affect processing.
 * @see src/cia_sie/core/enums.py - BasketType
 */
export type BasketType = 'LOGICAL' | 'HIERARCHICAL' | 'CONTEXTUAL' | 'CUSTOM'

/**
 * Claude model tiers for dynamic selection
 * @see src/cia_sie/core/enums.py - AIModelTier
 */
export type ModelTier = 'HAIKU' | 'SONNET' | 'OPUS'

/**
 * Status of AI response validation
 * @see src/cia_sie/core/enums.py - ValidationStatus
 */
export type ValidationStatus = 'VALID' | 'INVALID' | 'REMEDIATED'

/**
 * Types of narrative sections generated by the AI
 * @see src/cia_sie/core/enums.py - NarrativeSectionType
 */
export type NarrativeSectionType = 'SIGNAL_SUMMARY' | 'CONTRADICTION' | 'CONFIRMATION' | 'FRESHNESS'

/**
 * Time periods for AI usage tracking
 * @see src/cia_sie/core/enums.py - UsagePeriod
 */
export type UsagePeriod = 'DAILY' | 'WEEKLY' | 'MONTHLY'

/**
 * Roles in a conversation
 * @see src/cia_sie/core/enums.py - MessageRole
 */
export type MessageRole = 'user' | 'assistant'

